Smallest distinct window problem using c++
smv1999/CompetitiveProgrammingQuestionBank pull request #651
Opened 2021-07-19 10:07 UTC by vishvarana

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

Yes

### Description

Smallest distinct window in a string using c++ 

### Checklist

-  I've read the contribution guidelines.
- I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Issue #317 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

2021-07-19 11:33 UTC, smv1999 requested changes
Delete all those files that are not related to this PR.

2021-07-19 15:28 UTC, vishvarana commented
Changes made

2021-07-20 11:18 UTC, smv1999 requested changes
Great. Just add some comments to explain your core logic.

2021-07-22 09:53 UTC, vishvarana commented
Added comments in cpp file

2021-07-22 14:01 UTC, noviicee commented on Strings/smallestdistinctwindow.cpp
>              r++; #increment uptil the main string length
I guess there should be `//` instead of  `#` here.

2021-07-22 14:02 UTC, noviicee commented on Strings/smallestdistinctwindow.cpp
>              r++; #increment uptil the main string length
Line 27

2021-07-22 14:11 UTC, vishvarana commented
Changes made

2021-07-22 14:23 UTC, noviicee commented
LGTM 🚀

2021-07-22 15:02 UTC, smv1999 approved these changes

2021-07-22 15:02 UTC, merged