Implementation of LongestCommonPrefix in Python
smv1999/CompetitiveProgrammingQuestionBank pull request #659
Opened 2021-07-19 14:41 UTC by sravanyabendi

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

YES

### Description

Implementation of python program to find the longest common prefix amongst the given list of strings. If there is no common prefix then returning 0.

### Checklist

- [YES ] I've read the contribution guidelines.
- [YES ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

Longest-Common-Prefix #657

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

2021-07-20 11:34 UTC, smv1999 requested changes
Great. Just add the problem description at the top of the file (or link to the problem).

2021-07-21 05:08 UTC, sravanyabendi commented
I have added the description. Kindly, Please have a look into it.

2021-07-21 05:08 UTC, sravanyabendi commented
I have added the description. Kindly, Please have a look into it.

2021-07-21 15:23 UTC, smv1999 approved these changes

2021-07-21 15:23 UTC, merged