added partition equal subset sum
smv1999/CompetitiveProgrammingQuestionBank pull request #666
Opened 2021-07-19 17:19 UTC by bhagyashree-06

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?

yes
### Description

partition equal subset sum in python

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#319 
## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

2021-07-20 14:53 UTC, smv1999 requested changes

2021-07-20 14:53 UTC, smv1999 commented on General Questions/Partition_Equal_Subset_Sum.py
> +'''
Close this multi-line comment.

2021-07-20 16:22 UTC, bhagyashree-06 commented on General Questions/Partition_Equal_Subset_Sum.py
> +'''
done.

2021-07-21 05:52 UTC, noviicee reviewed
@bhagyashree-06 Modify the code to take dynamic  input from user.

2021-07-25 07:10 UTC, bhagyashree-06 commented
@noviicee, done!
kindly check

2021-07-25 08:02 UTC, noviicee commented
@bhagyashree-06 The entire code is a copy-paste from GfG. Even the comments!

2021-07-26 16:33 UTC, smv1999 commented
> @bhagyashree-06 The entire code is a copy-paste from GfG. Even the comments!

Well that goes against the [Contributing Guidelines](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md).

2021-07-26 17:17 UTC, closed without merging