Added remove duplicates
smv1999/CompetitiveProgrammingQuestionBank pull request #813
Opened 2021-07-30 06:05 UTC by siddhi-244

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
Yes
(Write your answer here.)

### Description
Added remove duplicates in cpp in recursion folder.
(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

#728 

## Fill up the DCP form 

If you are a part of DCP 21, fill up this [form](https://docs.google.com/forms/d/e/1FAIpQLSeRAJnHE4eAa_W0IUeNZgheiy5POX3I3tQB7DtFsiB13D5w2g/viewform) after the PR is merged.

### The links provided in the form will be checked thoroughly, if someone tries fooling around, strict actions will be taken against the individual.

2021-07-30 14:20 UTC, smv1999 requested changes
Just add a small description of the problem at the top of the file.

2021-07-30 15:53 UTC, siddhi-244 commented
> Just add a small description of the problem at the top of the file.

Done !

2021-07-31 13:48 UTC, siddhi-244 commented
@smv1999 done

2021-08-01 14:04 UTC, smv1999 approved these changes

2021-08-01 14:04 UTC, merged